blog/urls.py
from django.contrib import admin
from django.urls import path, include
from main import urls as main_urls
from users import urls as users_urls
from blog import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(main_urls)),
    path('users/', include(users_urls))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import (
    index, get_posts, get_post,
    create_post, edit_post, delete_post,
    search, contacts, about
)

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('posts/', get_posts, name='get_posts'),
    path('posts/<int:pk>/', get_post, name='get_post'),
    path('create_post/', create_post, name='create_post'),
    path('posts/<int:pk>/edit/', edit_post, name='edit_post'),
    path('posts/<int:pk>/delete/', delete_post, name='delete_post'),
    path('posts/search/', search, name="search"),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about')
]

users/urls.py
from django.urls import path
from .views import registration, log_in, log_out, get_user_info

app_name = 'users'

urlpatterns = [
    path('registration/', registration, name='registration'),
    path('log_in/', log_in, name='log_in'),
    path('log_out/', log_out, name='log_out'),
    path('<int:pk>/', get_user_info, name='get_user_info')
]

main/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    text = models.TextField(blank=True, null=True, verbose_name='Текст поста')
    image = models.ImageField(upload_to='post_images/', blank=True, null=True, verbose_name='Изображение поста')
    created_date_time = models.DateTimeField(default=timezone.now, editable=False)
    publication_date = models.DateTimeField(null=True, editable=False)

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ['title'] # '-title' - сортировка по убыванию

    def publish(self):
        self.publication_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

main/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post

        exclude = ['author']

main/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import PostForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse
# from django.db.models import Q

# Create your views here.

menu = [
    {'url_title': 'Блог', 'path_name': 'main:index'},
    {'url_title': 'Посты', 'path_name': 'main:get_posts'},
    {'url_title': 'Создать пост', 'path_name': 'main:create_post'},
    {'url_title': 'Контакты', 'path_name': 'main:contacts'},
    {'url_title': 'О сайте', 'path_name': 'main:about'}
]


def get_posts(request, query_results=None):
    if query_results is None:
        posts = Post.objects.all()
    else:
        posts = query_results

    title = 'Посты'

    context = {'menu': menu, 'title': title, 'posts': posts}

    return render(request, template_name='main/posts.html', context=context)


def index(request):
    title = 'Блог'

    return render(request, 'main/index.html', context={'menu': menu, 'title': title})


@login_required
def create_post(request):
    if request.method == 'GET':
        form = PostForm()

        title = 'Создать пост'

        context = {'menu': menu, 'title': title, 'form': form}

        return render(request, 'main/create_post.html', context=context)
    
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)

        if form.is_valid():
            post = Post()

            post.author = request.user
            post.title = form.cleaned_data['title']
            post.text = form.cleaned_data['text']
            post.image = form.cleaned_data['image']
            
            post.publish()

            url = reverse('main:get_posts')

            return redirect(url)
        

def edit_post(request, pk):
    post = Post.objects.get(pk=pk)
    
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)

        if form.is_valid():
            form.save()
        
            return redirect('main:get_post', pk=pk)
        
    elif request.method == 'GET':
        form = PostForm(instance=post)

        title = 'Редактировать пост'

        context = {'menu': menu, 'title': title, 'form': form}

        return render(request, 'main/edit_post.html', context)
    

def delete_post(request, pk):
    post = Post.objects.filter(pk=pk).first()
    
    if request.method == 'GET':
        title = 'Удалить пост'

        context = {'menu': menu, 'title': title}

        return render(request, 'main/delete_post.html', context)

    elif request.method == 'POST':
        if "delete" in request.POST:
            post.delete()

            return redirect('main:get_posts')
        
        elif "cancel" in request.POST:
            return redirect('main:get_post', pk)
        

def get_post(request, pk):
    post = Post.objects.get(pk=pk)

    title = f'{post.title}'

    context = {'menu': menu, 'title': title, 'post': post}

    return render(request, 'main/post.html', context=context)


def search(request):
    query = request.GET.get('query')
    
    # Фильтрация по заголовку и тексту поста
    # title_text_filter = Q(title__contains=query) | Q(text__contains=query)
    #
    # query_results = Post.objects.filter(title_text_filter)

    query_results = Post.objects.filter(author__username=query)

    return get_posts(request, query_results)


def contacts(request):
    title = 'Контакты'

    context = {'menu': menu, 'title': title}

    return render(request, 'main/contacts.html', context=context)


def about(request):
    title = 'О сайте'

    context = {'menu': menu, 'title': title}

    return render(request, 'main/about.html', context=context)

main/templates/main/about.html
{% extends "main/base.html" %}

{% block content %}
<h1>О сайте</h1>
{% endblock content %}

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{{title}}</title>

    <link rel="stylesheet" href="{% static 'CSS/bootstrap.min.css' %}" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    {% if user.is_authenticated %}
    Привет, {{user.username}}
    <p><a href="{% url 'users:log_out' %}">Выйти из аккаунта</a></p>
    {% endif %}

    {% if not user.is_authenticated %}
    <ul>
        <li><a href="{% url 'users:registration' %}">Создать аккаунт</a></li>
        <li><a href="{% url 'users:log_in' %}">Войти</a></li>
    </ul>
    {% endif %}

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url menu.0.path_name %}">{{menu.0.url_title}} <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url menu.1.path_name %}">{{menu.1.url_title}}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url menu.2.path_name %}">{{menu.2.url_title}}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url menu.3.path_name %}">{{menu.3.url_title}}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url menu.4.path_name %}">{{menu.4.url_title}}</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block head %}
    {% endblock head %}

    {% block content %}
    {% endblock content %}

    <script src="{% static 'JavaScript/jquery-3.3.1.slim.min.js' %}" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="{% static 'JavaScript/popper.min.js' %}" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="{% static 'JavaScript/bootstrap.min.js' %}" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/contacts.html
{% extends "main/base.html" %}

{% block content %}
<h1>Контакты</h1>
{% endblock content %}

main/templates/main/create_post.html
{% extends "main/base.html" %}

{% block head %}
<h1>Создать пост</h1>
{% endblock head %}

{% block content %}
<form action="{% url 'main:create_post' %}" method="POST" enctype="multipart/form-data">
{% csrf_token %}
    {{form.as_p}}
    <button type="submit">Создать пост</button>
</form>
{% endblock content %}

main/templates/main/delete_post.html
{% extends "main/base.html" %}

{% block content %}
<p>Вы уверены, что хотите удалить этот пост?</p>

<form method="POST">
{% csrf_token %}
    <button type="submit" name="delete">Удалить</button>
    <button type="submit" name="cancel">Отменить</button>
</form>
{% endblock content %}

main/templates/main/edit_post.html
{% extends "main/base.html" %}

{% block content %}
<h1>Внести изменения в пост</h1>

<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
    {{form.as_p}}
    <button type="submit">Применить изменения</button>
</form>
{% endblock content %}

main/templates/main/index.html
{% extends "main/base.html" %}

{% block head %}
<h1>Блог</h1>
{% endblock head %}

main/templates/main/post.html
{% extends "main/base.html" %}
{% load thumbnail %}

{% block head %}
<h1>Информация о посте</h1>
{% endblock head %}

{% block content %}
<p>Автор - {{post.author}}</p>
<p>Заголовок - {{post.title}}</p>
<p>Текст - {{post.text}}</p>

{% thumbnail post.image '300x300' as img %}
<img src="{{img.url}}" height="{{img.height}}" width="{{img.width}}">
{% endthumbnail %}

<p>Дата и время создания - {{post.created_date_time}}</p>
<p>Дата публикации - {{post.publication_date}}</p>

<hr>

{% if request.user == post.author or request.user.is_superuser %}
<a href="{% url 'main:edit_post' pk=post.id %}">Редактировать</a>
<br>
<a href="{% url 'main:delete_post' pk=post.id %}">Удалить</a>
{% endif %}
{% endblock content %}

main/templates/main/posts.html
{% extends "main/base.html" %}

{% block content %}
<div align="center">
    <form action="{% url 'main:search' %}" method="GET">
        <input type="text" name="query">
        <button type="submit">Найти</button>
    </form>
<div>

<table border=1 align='center'>
    <tr>
        <th>Автор</th>
        <th>Заголовок</th>
        <th>Текст</th>
        <th>Дата и время создания</th>
        <th>Дата публикации</th>
    </tr>
    {% for post in posts %}
    <tr>
        <td align='center'><a href="{% url 'users:get_user_info' pk=post.author.id %}">{{post.author}}</a></td>
        <td align='center'><a href="{% url 'main:get_post' pk=post.id %}">{{post.title}}</a></td>
        <td align='center'>{{post.text}}</td>
        <td align='center'>{{post.created_date_time}}</td>
        <td align='center'>{{post.publication_date}}</td>
    <tr>
    {% endfor %}
</table>
{% endblock content %}